// GET POSTS
const GET_POSTS_START = 'GET_POSTS_START';
const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
const GET_POSTS_ERROR = 'GET_POSTS_ERROR';

// DELETE POST
const DELETE_POST_START = 'DELETE_POST_START';
const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
const DELETE_POST_ERROR = 'DELETE_POST_ERROR';

export {
    GET_POSTS_START,
    GET_POSTS_SUCCESS,
    GET_POSTS_ERROR,
    DELETE_POST_START,
    DELETE_POST_SUCCESS,
    DELETE_POST_ERROR,
};
